#!/usr/bin/env bash

set -euo pipefail

clean() { rm -r -f www/; }

copy_assets() {
    cp -r healthcare/pubs   www/healthcare
    cp -r healthcare/media  www/healthcare
    cp    style.css         www/
}

build_webpages() {
    markdowns=(
        index.md
        healthcare/index.md
        secure-by-design/index.md
    )
    for markdown in "${markdowns[@]}"; do
        html="www/${markdown%.md}.html"
        mkdir -p "$(dirname "$html")"
        pandoc -t html5 --css=/style.css --standalone "$markdown" -o "$html"
    done
}

clean
mkdir -p www/healthcare
copy_assets
build_webpages
