#!/usr/bin/env bash

set -euo pipefail

clean() { rm -r -f www/; }

copy_assets() {
    cp -r pubs      www/
    cp    style.css www/
}

build_webpages() {
    markdowns=(
        index.md
        healthcare.md
        secure-by-design/index.md
    )
    for markdown in "${markdowns[@]}"; do
        html="www/${markdown%.md}.html"
        mkdir -p "$(dirname "$html")"
        pandoc -t html5 --css=style.css --standalone "$markdown" -o "$html"
    done
}

clean
mkdir -p www/
copy_assets
build_webpages
